include ../scripts/Makefile

all :
	g++ -c src/Select_func.cpp -I ../Factory/ -I ../func/Exit/src/ -I ../func/Chat/src/ -I ../func/Look/src -I ../Data/src -I ../Abstract/src/ -o src/Select_func.o

clean :
	rm -f src/Select_func.o
