CC := g++ -lpthread -lsqlite3
Target := client
Modules += main  my_stock Start Abstract Data Pass interface my_scanf Select_func func Factory
Allobjs := main/src/*.o  Select_func/src/*.o interface/src/*.o my_scanf/src/*.o Pass/src/*.o Data/src/*.o my_stock/src/*.o Start/src/*.o Abstract/src/*.o  
Allobjs += Factory/FuncFactory/src/FuncFactory.o  func/*/src/*.o