CC := g++ -lpthread -lsqlite3
Target := client
Modules += main Init my_stock Start Abstract Data Pass interface my_scanf Select_func func 
Allobjs := main/src/*.o  Select_func/src/*.o interface/src/*.o my_scanf/src/*.o Pass/src/*.o Data/src/*.o Init/src/*.o my_stock/src/*.o Start/src/*.o Abstract/src/*.o  
Allobjs += func/Look/src/*.o func/Chat/src/Chat.o