include ../../scripts/Makefile

all :
	g++ -c src/FuncFactory.cpp -I src/ -I ../../my_scanf/src/ -I ../ -I ../../func/Exit/src/ -I ../../func/Chat/src/ -I ../../func/Look/src/ -I ../../Abstract/src/ -o src/FuncFactory.o

clean :
	rm -f src/FuncFactory.o
	
