include ../../scripts/Makefile

all :
	g++ -c src/AllChat.cpp -I src/ -I ../../main/src/ -I ../../Data/src/ -I ../../Select_func/src/ -I ../../Pass/src/ -I ../../Start/src/ -I ../../Abstract/src/ -o src/AllChat.o

clean :
	rm -f src/*.o
