include ../scripts/Makefile

all :
	g++ -c -I ../my_scanf/src/ -I ../interface/src/ -I ../Pass/src/ -I ../Select_func/src/ -I ../Data/src/ -I ../Abstract/src/ src/Start.cpp -o src/Start.o

clean :
	rm -f src/Start.o
