include ../../scripts/Makefile

all :
	g++ -c src/FuncFactory.cpp -I ../../func/Remove/src/ -I ../../func/OffChat/src/ -I ../../func/OnChat/src/ -I ../../func/Record/src/ -I ../../func/Exit/src/ -I ../../func/Text/src/ -I ../../func/Help/src/ -I ../../func/Change_Passwd/src/ -I ../../func/Change_Name/src/ -I src/ -I ../../my_scanf/src/ -I ../ -I ../../func/Face/src/ -I ../../func/Fast/src/ -I ../../func/AllChat/src/ -I ../../func/Out/src/ -I ../../func/Chat/src/ -I ../../func/Look/src/ -I ../../Abstract/src/ -o src/FuncFactory.o

clean :
	rm -f src/FuncFactory.o
	
