include ../../scripts/Makefile

all :
	g++ -c src/Exit.cpp -I src/ -I ../../Data/src/ -I ../../Select_func/src/ -I ../../Pass/src/ -I ../../Start/src/ -I ../../Abstract/src/ -o src/Exit.o

clean :
	rm -f src/*.o
