include ../scripts/Makefile

all :
	g++ -c src/main.cpp -I ../my_scanf/src/ -I ../interface/src/ -I ../Data/src/ -I ../Pass/src/ -I ../Select_func/src/  -I ../Abstract/src/ -I ../Start/src -I ../my_stock/src -o src/main.o
clean :
	rm -f src/main.o
