include ../scripts/Makefile

all :
	g++ -c src/Select_func.cpp -I src/ -I ../Factory/  -I ../my_scanf/src/ -I ../interface/src/ -I ../Pass/src/ -I ../Start/src -I ../Data/src -I ../Abstract/src/ -o src/Select_func.o

clean :
	rm -f src/Select_func.o
