CC := g++ -lpthread -lsqlite3
Target := serve
Modules += main Init my_stock Start Abstract Data Pass Select_func
Allobjs := main/src/*.o Select_func/src/*.o Pass/src/*.o Init/src/*.o my_stock/src/*.o Start/src/*.o Abstract/src/*.o Data/src/*.o
