CC := g++ -lpthread -lsqlite3
Target := serve
Modules += main  Abstract Data my_stock Start Pass Select_func func Factory
Allobjs := main/src/*.o  Abstract/src/*.o Data/src/*.o my_stock/src/*.o Start/src/*.o Pass/src/*.o Select_func/src/*.o     
Allobjs += Factory/FuncFactory/src/FuncFactory.o  func/Look/src/*.o func/Chat/src/Chat.o func/Exit/src/Exit.o 