CC := g++ -lpthread -lsqlite3
Target := serve
Modules += main Init Abstract Data my_stock Start Pass Select_func func
Allobjs := main/src/*.o Init/src/*.o Abstract/src/*.o Data/src/*.o my_stock/src/*.o Start/src/*.o Pass/src/*.o Select_func/src/*.o     
Allobjs += func/Look/src/*.o func/Chat/src/Chat.o 