include ../scripts/Makefile

all :
	g++ -c -I ../Select_func/src/ -I ../interface/src/ -I ../my_scanf/src/ -I ../Start/src/ -I ../Data/src/ -I ../Abstract/src/ -I src/ src/Pass.cpp  -o src/Pass.o

clean :
	rm -f src/Pass.o
