include ../../scripts/Makefile

all :
	g++ -c src/Change_Name.cpp -I src/  -I ../../my_scanf/src/ -I ../../interface/src/ -I ../../Pass/src/ -I ../../Select_func/src/ -I ../../Data/src/ -I ../../Start/src/ -I ../../Abstract/src/ -o ../Change_Name/src/Change_Name.o

clean :
	rm -f src/*.o
