include ../../scripts/Makefile

all :
	g++ -c src/Fast.cpp -I src/  -I ../../my_scanf/src/ -I ../../interface/src/ -I ../../Pass/src/ -I ../../Select_func/src/ -I ../../Data/src/ -I ../../Start/src/ -I ../../Abstract/src/ -o ../Fast/src/Fast.o

clean :
	rm -f src/*.o
