include ../../scripts/Makefile

all :
	g++ -c src/Text.cpp -I src/  -I ../../my_scanf/src/ -I ../../interface/src/ -I ../../Pass/src/ -I ../../Select_func/src/ -I ../../Data/src/ -I ../../Start/src/ -I ../../Abstract/src/ -o ../Text/src/Text.o

clean :
	rm -f src/*.o
