include ../../scripts/Makefile

all :
	g++ -c src/Record.cpp -I src/ -I ../../main/src/ -I ../../Data/src/ -I ../../Select_func/src/ -I ../../Pass/src/ -I ../../Start/src/ -I ../../Abstract/src/ -o src/Record.o

clean :
	rm -f src/*.o
