include ../scripts/Makefile

all :
	g++ -c -I ../Data/src/ -I ../Select_func/src/ -I ../interface/src/ -I ../my_scanf/src/ -I ../Pass/src/ -I ../my_stock/src/ -I ../Start/src/ src/Init.cpp -I ../Init/src -o src/Init.o

clean :
	rm -f src/Init.o