include ../../scripts/Makefile

all :
	g++ -c src/Look.cpp -I src/ -I ../../Data/src/ -I ../../Select_func/src/ -I ../../Pass/src/ -I ../../Start/src/ -I ../../Abstract/src/ -o src/Look.o

clean :
	rm -f src/Look.o
