include ../scripts/Makefile

all :
	g++ -c -I src/  -I ../main/src/ -I ../Pass/src/ -I ../Select_func/src/ -I ../Abstract/src/ -I ../Data/src/ src/Start.cpp -o src/Start.o

clean :
	rm -f src/Start.o
